import Head from 'next/head';
import Image from 'next/image';
import { Suspense, useState } from 'react';
import { DataLoader } from '../src/components/DataLoader';
import { NoSSR } from '../src/components/NoSSR';
import { RenderingNotifier } from '../src/components/RenderingNotifier';
import { SometimesSuspend } from '../src/components/SometimesSuspend';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [count, setCount] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <NoSSR>
          <RenderingNotifier name="outside-Suspense" />
          <Suspense fallback={<p>Test ...</p>}>
            <SometimesSuspend />
            <RenderingNotifier name="inside-Suspense" />
            <button
              className="border p-1"
              onClick={() => setCount((c) => c + 1)}
            >
              {count}
            </button>
          </Suspense>
          <Suspense fallback={<p>Loading ...</p>}>
            <DataLoader />
          </Suspense>
        </NoSSR>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
